### ISSUE TITLE
Save tracking

### ISSUE THREAD

**Issue by zachmoore12** [zachmoore12/lovetapp#8]
On submit,

- [x] Get current score
- [x] Add/Subtract appropriately 
- [x] Check for note, and save appropriately
~~- Sync remotely if online~~
